Import project
cauldron/activity-browser pull request #39
Opened 2024-08-12 18:37 UTC by zoltanszocs

## Checklist

- [ ] Keep pull requests small so they can be easily reviewed.
- [ ] Update the documentation, please follow the [numpy style guide](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] Update tests.
- [ ] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `feature`, `ui`, `change`, `documentation`, `breaking`, `ci`
      as they show up in the changelog.
- [ ] Link this PR to related issues by using [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
- [ ] Add a milestone to the PR for the intended release.
- [ ] Request a review from another developer.

2024-08-12 19:12 UTC, cmutel requested changes
Nice!
<img width="408" alt="Screenshot 2024-08-12 at 21 05 17" src="https://github.com/user-attachments/assets/b8fe269c-a605-4722-99f9-163e969d6919">
- [ ] Can we add some more space here? It feels quite cramped.
- [ ] Can we please give some indication on *why* the "create project" button is disactivated, i.e. warning text which states that the project name already exists
- [ ] Can we add another checkbox to switch to the project after import? The code to run would be `bw2data.projects.set_current(<new_project_label>)`

2024-08-12 19:12 UTC, cmutel commented on activity_browser/actions/project/project_remote_import.py
> +        self.table.populate(url_path + self.remote_catalogue.text())
Let's use `urllib.parse.urljoin` here instead.

2024-08-13 07:37 UTC, zoltanszocs commented on activity_browser/actions/project/project_remote_import.py
> +        self.table.populate(url_path + self.remote_catalogue.text())
Done

2024-08-13 10:23 UTC, zoltanszocs commented
- Added a bit more space between components - I was not entirely sure where you wanted more space, increasing the global spacing in the layout seemed strange. Let me know how this looks.
- Added status label at the bottom, displaying what is the next necessary step: load catalogue, select project, project already exists
- Added handling for the case when there is no valid catalogue loaded
- Added busy indication for the catalogue loading and project importing

2024-08-13 10:34 UTC, merged